language: node_js
node_js:
- 8.1
script: 'true'
deploy:
  provider: s3
  access_key_id: AKIAI4ZO66BREZY3542Q
  secret_access_key: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
  bucket: codin-ui
  local-dir: dist
  upload-dir: dist
  acl: public_read
  on:
    repo: souvikckr/codInUI
    branch: tslint-souvik
